### ISSUE TITLE
Spam from webforms

### ISSUE THREAD

**Issue by CaroRob** [MassLegalHelp/MassLegalHelp#15]
@kpolymorphic as we saw yesterday we are now up to over 90,000 submissions from the contact-us form and the majority of these are spam.
We need to prevent more spam coming in on this webform and others.
We agreed that 

1. we would start with asking you to install ReCaptcha and configure first on the [Contact Us](https://www.masslegalhelp.org/contact-us) webform
2. Depending on how that goes either use Features to help configure the other forms or do them individually.
We are hoping that Features will be useful because we need to learn how to and begin using this module.
3. I am supposed to give you a list of all the webforms that need ReCaptcha.
4. Our translated webforms are not as clear cut as we would have hoped. so the next form to add ReCaptcha to is our [Feedback](https://www.masslegalhelp.org/node/65666) form. Right now we only use this in English.

First day back at the office after 3 weeks out - I couldn't figure out how to create a new issue! Then office people started asking me for stuff.

 @purplesky2016  and I are spending this morning cleaning up our webforms. 
Our [email this article to a friend](https://www.masslegalhelp.org/tell-a-friend-form) form is  translated by configuring translated strings in Webform Localization.

We found the strings we are using to translate "email this article to a friend" here:

- https://www.masslegalhelp.org/admin/config/regional/translate/translate
- Limit search to Webform Localization

We are planning on translating [Tell LAC about the program that denied you an Interpreter](https://www.masslegalhelp.org/interpreter) in the same way - currently there is an individual webform for each language.

However, as I am writing this we deleted translated forms we were not using on the dev site which seems to have completely screwed up the menus on the left side of the page!

Lily and I are exploring - if these are somehow connected.

**Comment by kpolymorphic** [comment]
@CaroRob - I am creating a copy of this issue in my ticketing system. Not sure if you wanted it in yours too.

**Comment by CaroRob** [comment]
Ah yes, --- not sure how to keep track of the 2 ticketing systems... how to link between them, just reopened  issue you just closed cause ... ima idiot

**Comment by CaroRob** [comment]
In GollyGood ticket system[ Issue #56](https://github.com/GollyGood/mlri-mlh/issues/56#issuecomment-430331334)
